Домашка 11.08 + домашка за 04.08(повторно)(Владимир)
therezor/phpacademy pull request #16
Opened 2017-09-06 09:04 UTC by Bob-Paulson

Я не понял куда делся мой предыдущий pull request = (. Чтобы создать этот нужно было отключить предыдущий. Без этого его создать не получалось. И по ходу он вообще удалился (

2017-09-06 11:40 UTC, therezor requested changes

2017-09-06 11:40 UTC, therezor commented on home_task0.php
> +		Error_reporting(E_ALL);
error_reporting  - с маленькой буквы (хотя работает и так)

2017-09-06 11:40 UTC, therezor commented on home_task0.php
> +		echo "Меня зовут: ",$name,"<br/>";
"Меня зовут $name <br/>"
'Мне ' . $age

2017-09-06 11:40 UTC, therezor commented on home_task0.php
> +		}else{
} elseif (...) {
} elseif(...) {

elseif и else if - не совсем одно и тоже

2017-09-06 11:40 UTC, therezor commented on home_task0.php
> +			case '-':
case '-' 2 раза повторяется

2017-09-06 11:40 UTC, therezor commented on home_task0.php
> +		if($num_a > $num_b){
max($a,$b)

2017-09-06 11:40 UTC, therezor commented on home_task1.0.php
> +	echo $result,"<br/>";
Объявить переменную $result забыли

2017-09-06 11:40 UTC, therezor commented on home_task1.4.php
> +$arr[$min_index] = $buf;
Супер!

2017-09-06 21:01 UTC, Bob-Paulson commented on home_task0.php
> +		}else{
Могу ошибаться но Вы вроде говорили что в php можно и так и так писать , а вот в js работает только else if.

2017-09-06 21:05 UTC, Bob-Paulson commented on home_task0.php
> +			case '-':
Ёпрст....тут + должен быть = (

2017-09-06 21:05 UTC, Bob-Paulson commented on home_task0.php
> +		if($num_a > $num_b){
Про эти ф-ии помнил, тут решил в ручную попрактиковаться )

2017-09-06 21:07 UTC, Bob-Paulson commented on home_task1.0.php
> +	echo $result,"<br/>";
Вот это даа (

2017-09-07 07:56 UTC, therezor commented on home_task0.php
> +		if($num_a > $num_b){
Хорошо, засчитано.

2017-09-07 07:57 UTC, therezor commented on home_task0.php
> +		}else{
можно, но это разные вещи немножко

2017-11-20 06:01 UTC, closed without merging