arrays_loops_tasks
therezor/phpacademy pull request #7
Opened 2017-08-13 12:59 UTC by mykytadenysenkov

2017-08-14 07:37 UTC, therezor requested changes

2017-08-14 07:37 UTC, therezor commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/14.php
> +foreach ($arr as $val) {
дублирование кода. Создайте еще один масив с числами 2,3,4 и проверьте на вхождение

2017-08-14 07:37 UTC, therezor commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/16.php
> +    if (($key + 1) % 3 == 0) echo '<br>';
```
if () {
} else {
}
```

2017-08-14 07:37 UTC, therezor commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/17.php
> +    else echo $value . '<br>';
} else {
}

2017-08-14 07:37 UTC, therezor commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/18.php
> +    else echo $day . '<br>';
Тоже самое, что и выше

2017-08-14 07:37 UTC, therezor commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/19.php
> +$today = "вс";
Текущий день должен храниться в переменной $day.

2017-08-14 07:37 UTC, therezor commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/23.php
> +while($value > 0) {
Должно считать сумму
123 = 1 + 2 + 3

2017-08-14 07:37 UTC, therezor commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/23.php
> +        $value = @abs($_GET['value']);
Зачем используете значение по модулю и проверяете, что больше 0?
Зачем используете символ @ (подавление ошибок)

2017-08-14 07:37 UTC, therezor commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/24.php
> +        $numeral = @abs($_GET['numeral']);
Замечания, что и выше

2017-08-14 07:47 UTC, mykytadenysenkov commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/23.php
> +        $value = @abs($_GET['value']);
Значение по модулю - для того, чтобы с отрицательными числами тоже работало. Проверка больше 0, чтобы работало со string, которые начинаются с числа, например, "12x". 
Подавление ошибок - чтобы изначально, когда массив $_GET пустой, на экране не было нотиса или ошибки (не помню точно, что там).

2017-08-14 07:53 UTC, therezor commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/23.php
> +        $value = @abs($_GET['value']);
А как туда попадет значение меньше нуля?
Подавление ошибок не рекомендуется. 
Вместо этого используйте isset($var)

2017-08-14 08:11 UTC, mykytadenysenkov commented
Подскажите, пожалуйста, я исправил файлы согласно Вашим рекомендациям в phpstorm. И сделал push  в свой репозиторий. Как теперь добавить измененные файлы в этот пулл реквест?

2017-08-14 08:17 UTC, therezor commented
Оно автоматически добавляет новые комиты в PR

2017-08-15 07:35 UTC, mykytadenysenkov commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/23.php
> +while($value > 0) {
Код это и делает.  В чем вопрос?

2017-08-15 07:35 UTC, mykytadenysenkov commented on 31.07_FSTK/Denysenkov_Mykyta/arrays_loops_tasks/23.php
> +        $value = @abs($_GET['value']);
Пользователь может ввести отрицательное значение

2017-09-03 08:45 UTC, closed without merging